-- MySQL Script generated by MySQL Workbench
-- Wed Jun 15 21:29:47 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema inventario
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `inventario` ;

-- -----------------------------------------------------
-- Schema inventario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inventario` DEFAULT CHARACTER SET utf8 ;
USE `inventario` ;

-- -----------------------------------------------------
-- Table `inventario`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`cliente` ;

CREATE TABLE IF NOT EXISTS `inventario`.`cliente` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `edad` VARCHAR(45) NULL,
  `genero` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventario`.`producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`producto` ;

CREATE TABLE IF NOT EXISTS `inventario`.`producto` (
  `codigo` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `precio` DOUBLE NULL,
  `inventario` INT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `inventario`.`cliente_has_producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `inventario`.`cliente_has_producto` ;

CREATE TABLE IF NOT EXISTS `inventario`.`cliente_has_producto` (
  `cliente_id` INT NOT NULL,
  `producto_codigo` INT NOT NULL,
  PRIMARY KEY (`cliente_id`, `producto_codigo`),
  INDEX `fk_cliente_has_producto_producto1_idx` (`producto_codigo` ASC) VISIBLE,
  INDEX `fk_cliente_has_producto_cliente_idx` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_has_producto_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `inventario`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_producto_producto1`
    FOREIGN KEY (`producto_codigo`)
    REFERENCES `inventario`.`producto` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
